### ISSUE TITLE
Human friendly experience

### ISSUE THREAD

**Issue by xlstefan** [xlstefan/SentimentAnalysis#6]
I as a sentiment annotator
want to use arrows on a keyboard (left, right to change score from -5 to 5) to annotate each sentence and on key "Enter" to confirm the score and jump to next not annotated sentence

**Comment by xlstefan** [comment]
@Ruskopp @MarijaJankovic623 
What do you think, should we invest some time in this?

**Comment by MarijaJankovic623** [comment]
I wouldn't because we already have scroller and I think that's enough for annotating.
